security:
  encoders:
    App\Application\Entity\User:
      algorithm: auto
  providers:
    users:
      entity:
        class: App\Application\Entity\User
        property: pseudo
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    sport:
      anonymous: lazy
      provider: users
      pattern: ^/sport
      logout:
        path: security_logOut
      guard:
        authenticators:
          - App\Application\Security\Guard\Sport\WebAuthenticator
    admin:
      anonymous: lazy
      provider: users
      pattern: ^/admin
      logout:
        path: security_logOut
      guard:
        authenticators:
          - App\Application\Security\Guard\Admin\WebAuthenticator
    main:
      anonymous: lazy
      provider: users
      logout:
        path: security_logOut
      guard:
        authenticators:
          - App\Application\Security\Guard\WebAuthenticator

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - {path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - {path: ^/api/V1/documentation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - {path: ^/api/ui, roles: IS_AUTHENTICATED_FULLY }
  # - { path: ^/admin, roles: ROLE_ADMIN }
  # - { path: ^/profile, roles: ROLE_USER }

