services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\Domain\Programme\:
    resource: '../../*'
  App\Domain\Programme\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']