services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\Domain\Sport\:
    resource: '../../*'
  App\Domain\Sport\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']