api-connexion:
  path: /api-connexion
  controller: App\Domain\Api\Controller\ConnexionApi

create-token:
  path: /api/create-token
  controller: App\Domain\Api\Controller\CreateToken

api-articles:
  path: /api/article-{id}
  controller: App\Domain\Api\Controller\ReadArticleApi
  methods: GET

api-listing-articles:
  path: /api/indexapi
  controller: App\Domain\Api\Controller\ListingArticleApi
  methods: GET

api-create-article:
  path: /api/create-article
  controller: App\Domain\Api\Controller\CreateArticleApi

api-create-article-form:
  path: /api/create-article-form
  controller: App\Domain\Api\Controller\CreateArticleForm